### ISSUE TITLE
Breaks with freshly installed dependencies

### ISSUE THREAD

**Issue by pstadler** [jsdoc2md/gulp-jsdoc-to-markdown#5]
There's currently a problem with the buffer mode when installing this module from scratch. I tried to debug it but eventually had to move on.

1. git clone
2. npm install
3. npm test
 
```bash
> gulp-jsdoc-to-markdown@1.2.0 test /Users/pstadler/GitHub/gulp-jsdoc-to-markdown
> tape test/*.js

TAP version 13
# streaming mode
ok 1 is a stream
ok 2 correct data
# buffer mode
not ok 3 plan != count
  ---
    operator: fail
    expected: 2
    actual:   0
  ...

1..3
# tests 3
# pass  2
# fail  1

npm ERR! Test failed.  See above for more details.
```

Thanks,
Patrick

**Comment by pstadler** [comment]
It's worth to mention that pinning the jsdoc-to-markdown dependency to any previous version didn't help.

**Comment by 75lb** [comment]
reproduced, thanks for letting me know. Looking into it. 

So, your docs don't generate at all at the moment?

**Comment by pstadler** [comment]
This is correct.

**Comment by 75lb** [comment]
isolated the issue, hopefully will be a quick fix

**Comment by pstadler** [comment]
Great :+1:

**Comment by pstadler** [comment]
Thanks for your quick response!

**Comment by 75lb** [comment]
fixed downstream in jsdoc-api, please update your plugin.. 

thanks for letting me know it was broken!
